### ISSUE TITLE
postLocalNotification - fireDate ignored

### ISSUE THREAD

**Issue by tststs** [wix/react-native-notifications#484]
In React Native 0.61.5
react-native-notifications 3.1.1

On android it doesn't matter what date i pass as fireDate, the notifications is fired immediately.

```js
const someLocalNotification = Notifications.postLocalNotification({
    fireDate: addSeconds(new Date(), 15),
    body: 'Local notificiation!',
    title: 'Local Notification Title',
  });
```

**Comment by songsterq** [comment]
You need to give it a ISO string. This works for me:
```javascript
    const payload = {
      body: details.message,
      title: details.title,
      sound: details.soundName,
      userInfo: details.data,
    };
    if (details.fireDate) {
      payload['fireDate'] = details.fireDate.toISOString();
    }
    Notifications.postLocalNotification(payload);
```

**Comment by tststs** [comment]
hey @songsterq

```js
const date = new Date('Apr 30, 2022');
const fireDate = date.toISOString();
  Notifications.postLocalNotification({
    fireDate,
    body: 'Local notificiation!',
    title: 'Local Notification Title',
  }, hash);
```

It also fires in the immediately.

**Comment by LuisRodriguezLD** [comment]
I am also experiencing this problem

**Comment by LeungMingFai** [comment]
same here. notification fired immediately
android
"react-native": "0.61.5",
"react-native-notifications": "^3.1.2",

**Comment by irondsd** [comment]
Same problem. Any workaround?

**Comment by wincjh** [comment]
+1

**Comment by NagashreeMedaMN** [comment]
+1
Does it work on iOS?

**Comment by LeungMingFai** [comment]
@irondsd i manage to implement local scheduled notification using react-native-firebase 5 instead.

https://rnfirebase.io/docs/v5.x.x/notifications/scheduling-notifications

**Comment by LeungMingFai** [comment]
> +1
> Does it work on iOS?

Didnt test it myself, but seems like it does, only android has this issue

**Comment by JaioSkura** [comment]
Any fix for this?

**Comment by sephiroth56** [comment]
Same here

**Comment by pitaman71** [comment]
Ran into this yesterday. It looks like fireDate isn't even in the payload format, which also caused my Typescript compiler to complain. I'm switching to Promises anyway else I'd fix this.

**Comment by hannojg** [comment]
If we look at the documentation:
https://wix.github.io/react-native-notifications/docs/localNotifications

We can see that for `postLocalNotification` the `fireDate` attribute is only in the iOS section (small apple icon in the title)

So, I guess, it really isn't implemented for android yet

**Comment by difaananda40** [comment]
any update?

**Comment by JaioSkura** [comment]
Hi!
I have done it in a fork, but still have to merge in the oficial repo. Hope to do it this week.

**Comment by difaananda40** [comment]
glad to hear that!

**Comment by renanliberato** [comment]
Hello everyone! Any news on that? I'm not familiar with developing native modules, but I would love to help testing it, as I am currently developing an Android app and I have just found out (the hard way haha) that the lib does not support it yet..

**Comment by douira** [comment]
btw I've [updated the docs](https://github.com/wix/react-native-notifications/pull/621) to show that scheduled notifications are not implemented on android yet.

**Comment by Fausto95** [comment]
Any idea of when this will be implemented?

**Comment by JaioSkura** [comment]
HI, I have done it in this fork: https://github.com/JaioSkura/react-native-notifications
You can use it if you want. I need some time to merge it in the oficial project because of the tests, there is something that is not passing the tests and I need some time to analize it. Anyway it is working, with no problems. 
If you want to use it , I think that you will have to build locally:
-Navigate to the root folder of the library
-yarn install
-run build

If you have any problem let me know and I will try to help!

**Comment by Fausto95** [comment]
Hi @JaioSkura 
First of, thanks for spending time implementing this feature in your fork. 
I have your fork published under https://github.com/CoorpAcademy/react-native-notifications and it now schedules the notification correctly. 

I’ve noticed that when you schedule 2 or so notifications with different fireDates in a row, it actually sends them all at once.. 

Is there anything you can help with?

**Comment by JaioSkura** [comment]
Hi @Fausto95 ! 

I am glad that my fork is useful for you. How are you scheduling this notifications? can you share somo code? In my app, I schedule up to 64 notifications at once at it works fine. 

Let me know!

**Comment by Fausto95** [comment]
@JaioSkura this is what I'm doing in my app: 
 
```typescript
const scheduleNotification = (title: string, body: string, id: number, index: number) => {
    const date = new Date(Date.now() + 20 * (index + 1) * 1000)
    const notification = {
      title,
      body,
      silent: false,
      userInfo: {},
      fireDate: date,
    };
    Notifications.postLocalNotification(notification, id);
  };
// scheduled for 20s after this function call
scheduleNotification('AwesomeNotification1', 'My awesome notification', 1231, 1);
// scheduled for 20s after previous function call
scheduleNotification('AwesomeNotification2', 'My awesome notification', 2231, 2);
// scheduled for 20s after previous function call
scheduleNotification('AwesomeNotification3', 'My awesome notification', 3231, 3);
```

**Comment by JaioSkura** [comment]
ups, can you check that the 'date' created for each notification corresponds to the momet that you want to fire it?

**Comment by Fausto95** [comment]
@JaioSkura, yes, it does correspond to the date I want it to be fired.

**Comment by infiniteline** [comment]
@JaioSkura, this is pretty exciting. I was unable to use react-native-notifications in my current project as I need local scheduled notifications. You mention that there is "something that is not passing the tests" that is holding back a merge. Can you elaborate at all or is it a mystery to you as well?

**Comment by alinz** [comment]
I was reading this thread, and I hate seeing multiple forked of the project. for me the elegant way is to use `patch` file and using `patch-package` module to apply the changes to node_modules. Eventually this library is going to implement this feature and we simply remove the patch file. I have created a patch file based on @JaioSkura implementation. simply create a folder in your root project call `patches` and create `react-native-notifications+3.3.4.patch` file under it. Then use the content of this [gist](https://gist.github.com/alinz/8ecc33066a8975f8e1d65740814a76f4). make sure to add `"postinstall": "patch-package"` to your package.json's scripts object.

**Comment by ZComwiz** [comment]
Feb 6 this issue was opened. It's Dec 3 today. Let's get this merged! (@alinz @irondsd @hannojg et al.)

**Comment by douira** [comment]
So this was resolved?

**Comment by hassanila97** [comment]
This feature should have been there in the first commit

**Comment by Fawaz456** [comment]
Is this resoved? As I am still facing the same issue that local notifications fired immediately independent of fireDate. Have tried with ISO String and unix time-stamp too. But no luck.

**Comment by zachnicoll** [comment]
Surely this can be merged in now, it appears as though it is working for the people who have tried it. This functionality is highly desired and it would be amazing to be able to use this library.

**Comment by a-eid** [comment]
still experiencing this on 

- react-native 0.64.1
- react-native-notifications ^3.4.2

**Comment by gabrielmoncea** [comment]
@wixmobile this issue wasn't supposed to be closed

**Comment by Allwithyou999** [comment]
> still experiencing this
> 
> * react-native 0.64.1
> * react-native-notifications ^3.4.2

did you resolve this issue?

**Comment by Jaybee4real** [comment]
Hello, was this issue solved?, i am still experiencing this issue

**Comment by douira** [comment]
see this PR: https://github.com/wix/react-native-notifications/pull/621
I added a note that it's not implemented yet. Maybe they've changed it by now but it did not work then.

**Comment by robgraeber** [comment]
Solution to this is using the more up-to-date package: `expo-notifications`

**Comment by AphexHenry** [comment]
what are we waiting to integrate it? it seems like a critical feature.

**Comment by zkteco-home** [comment]
same issue
