### ISSUE TITLE
Notifications.getInitialNotification() is undefined when click on notification in quite state [ANDROID]

### ISSUE THREAD

**Issue by Etaliya** [wix/react-native-notifications#958]

**Comment by silviaskura** [comment]
same hear

**Comment by silviaskura** [comment]
same here

**Comment by kristofb** [comment]
In which version of Android are you experiencing this problem?
It may be related to https://github.com/wix/react-native-notifications/pull/920

**Comment by Etaliya** [comment]
> In which version of Android are you experiencing this problem? It may be related to #920

Android 13

**Comment by kristofb** [comment]
Same for me in fact...

**Comment by kristofb** [comment]
This issue is still valid.

**Comment by kristofb** [comment]
May be solved by https://github.com/wix/react-native-notifications/pull/966

**Comment by greenimpala** [comment]
Still valid

**Comment by the-skins-app** [comment]
Indeed it is solved by #966 , well done @kristofb !!

*(using sdk 33)*

**Comment by oristian** [comment]
thanks @kristofb - works.  would appreciate a merge!

**Comment by volle241** [comment]
The problem still valid

**Comment by greenimpala** [comment]
You can apply a [patch](https://github.com/ds300/patch-package) for now @volle241. Although we still see the issue on some devices so I'm not 100% convinced this solves it.

[react-native-notifications+4.3.5.patch](https://github.com/wix/react-native-notifications/files/11881432/react-native-notifications%2B4.3.5.patch)

**Comment by diegoplatap** [comment]
If your provider is FCM, what works for me consistenly was to add yarn add @react-native-firebase/messaging and use:

messaging()
      .getInitialNotification()
      .then(remoteMessage => {
        if (remoteMessage) {
          console.log(
            'Notification caused app to open from quit state:',
            remoteMessage.notification,
          );
        }
})

**Comment by TwistedMinda** [comment]
Hi, is anyone still stuck on this issue? Because I am. Tried all the options provided here and there:
- applying the patch
- testing the recent react-native-notifications 5.0.0
- use firebase's getInitialNotification instead
but none of these helped

Recap of the bug:

Tapping a notification:
- opens correctly when app is on background
- opens correctly when app is quitted
- opens by restarting the activity when app is on foreground

The activity doesn't seem to really restart entirely: SplashScreen appears but the navigation state is preserved.
It would still be okay if getInitialNotification() would return the notification tapped, but it's not.

Am I the only one?

**Comment by zabojad** [comment]
@TwistedMinda in my case, it works. Can you share the code where you call `Notifications.getInitialNotification()` ?

**Comment by TwistedMinda** [comment]
@zabojad Hey, good to know it can work!

Well I don't really do anything fancy, just calling it:

```ts 
Notifications.getInitialNotification().then((notification) => {
  if (notification) {
    handleNotification(notification)  
  }
})
```
